services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
    volumes:
      - ./n8n-data:/home/node/.n8n
    user: "1000:1000"  # あなたのユーザーIDとグループIDに変更
    restart: always

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "127.0.0.1:11434:11434"
  #   volumes:
  #     - ./ollama-data:/root/.ollama
  #   restart: unless-stopped 